/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.raven;

/**
 *
 * @author heba
 */
public class Signin extends javax.swing.JPanel {

    /**
     * Creates new form SignUp
     */
    public Signin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        face = new javax.swing.JLabel();
        google = new javax.swing.JLabel();
        mailicone = new javax.swing.JLabel();
        loginPage = new javax.swing.JLabel();
        UsernameMail = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        done = new javax.swing.JButton();
        or = new javax.swing.JLabel();
        SigninButton = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        enterscreen = new javax.swing.JLabel();
        minus = new javax.swing.JLabel();
        loginLogo = new javax.swing.JLabel();
        Pname = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(599, 332));

        jPanel1.setBackground(new java.awt.Color(75, 98, 122));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        face.setIcon(new javax.swing.ImageIcon("/Users/Eslam/Desktop/icons/facebook.png")); // NOI18N

        google.setIcon(new javax.swing.ImageIcon("/Users/Eslam/Desktop/icons/google.png")); // NOI18N

        mailicone.setIcon(new javax.swing.ImageIcon("/Users/Eslam/Desktop/icons/gmail.png")); // NOI18N

        loginPage.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        loginPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginPage.setText("Login");

        UsernameMail.setForeground(new java.awt.Color(204, 204, 204));
        UsernameMail.setText("username/mail"); // NOI18N
        UsernameMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameMailActionPerformed(evt);
            }
        });

        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setToolTipText("");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        done.setForeground(new java.awt.Color(102, 102, 102));
        done.setLabel("Done");

        or.setForeground(new java.awt.Color(204, 204, 204));
        or.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        or.setText("or");

        SigninButton.setForeground(new java.awt.Color(102, 102, 102));
        SigninButton.setText("SignUp");

        close.setIcon(new javax.swing.ImageIcon("/Users/Eslam/Desktop/icons/close copy 2.png")); // NOI18N
        close.setMaximumSize(new java.awt.Dimension(15, 15));
        close.setMinimumSize(new java.awt.Dimension(15, 15));
        close.setPreferredSize(new java.awt.Dimension(15, 15));
        close.setSize(new java.awt.Dimension(48, 16));

        enterscreen.setIcon(new javax.swing.ImageIcon("/Users/Eslam/Desktop/icons/round.png")); // NOI18N

        minus.setIcon(new javax.swing.ImageIcon("/Users/Eslam/Desktop/icons/minus-sign.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(minus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterscreen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(face)
                                .addGap(18, 18, 18)
                                .addComponent(google)
                                .addGap(18, 18, 18)
                                .addComponent(mailicone))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField1)
                                    .addComponent(UsernameMail, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(loginPage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SigninButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(or, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterscreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(loginPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UsernameMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(done)
                .addGap(24, 24, 24)
                .addComponent(or)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SigninButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mailicone)
                    .addComponent(google)
                    .addComponent(face))
                .addContainerGap())
        );

        loginLogo.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 16)); // NOI18N
        loginLogo.setForeground(new java.awt.Color(255, 255, 255));
        loginLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLogo.setText("Login");

        Pname.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 12)); // NOI18N
        Pname.setForeground(new java.awt.Color(255, 255, 255));
        Pname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pname.setText("Raven");

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon("/Users/Eslam/Desktop/icons/ecommerce.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginLogo)
                .addGap(107, 107, 107)
                .addComponent(Pname)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void UsernameMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameMailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pname;
    private javax.swing.JButton SigninButton;
    private javax.swing.JTextField UsernameMail;
    private javax.swing.JLabel close;
    private javax.swing.JButton done;
    private javax.swing.JLabel enterscreen;
    private javax.swing.JLabel face;
    private javax.swing.JLabel google;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JLabel loginPage;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mailicone;
    private javax.swing.JLabel minus;
    private javax.swing.JLabel or;
    // End of variables declaration//GEN-END:variables
}
